### ISSUE TITLE
Playback Simulator Pin GPU to 100% on Apple Silicon

### ISSUE THREAD

**Issue by Firedude1** [Deep-Symmetry/beat-link-trigger#185] opened 2024-08-14 23:56 UTC
**Describe the bug**
When playback simulator window is opened, GPU usage shoots up to 100% on Macbook Pro with Apple M3 Max.

**To Reproduce**
1. Go to Network
2. Click on New Playback Window
3. Look at system resources monitor
4. See GPU usage maxed out

**Expected behavior**
For GPU not to be maxed out when opening a simulator window.

**Screenshots**
<img width="844" alt="Screenshot 2024-08-14 at 4 53 57 PM" src="https://github.com/user-attachments/assets/4527049c-9110-4c14-8291-a74a2721f272">

**Exceptions and Stack Traces**
Nothing out of the ordinary was displayed in logs.

**Desktop (please complete the following information):**
 - Beat Link Triger Version: Beat Link Trigger version 7.4.1 
 - Java Version: Java version 17.0.11, OpenJDK 64-Bit Server VM, Amazon.com Inc.
 - OS: Mac OS X 14.5

**Additional context**
Unfortunately not, hopefully this bug is reproducible on other systems.

**Comment by brunchboy** [comment] 2024-08-15 00:14
Before opening issues, it's best to discuss things in the [Zulip community](https://deep-symmetry.zulipchat.com/#narrow/stream/275322-beat-link-trigger), and then if we agree there seems to be an issue, we can direct you to the appropriate project.

In this case, it's unlikely we'll be able to do anything. The playback simulator doesn't interact with the GPU, indeed none of our code does, except indirectly through drawing graphics, and the playback simulator doesn't draw graphics. You may have found a Java bug, and if you can track it down further with Java performance analysis tools, they may be able to fix it. 

But perhaps you are running custom expressions that do something? Let's take this discussion to Zulip.

**Comment by brunchboy** [comment] 2024-08-15 00:17
Or, hmm, the playback window is animating things potentially. If you can track down what's going on, that would be helpful.

**Comment by brunchboy** [comment] 2024-08-15 00:26
When I have time to get back to BLT I'll see if I can reproduce this, and if there is any obvious way to fix it. But keep in mind that performance of the shallow playback simulator isn't a priority; it's much better to use real player hardware to truly test things.

**Comment by brunchboy** [comment] 2024-08-15 03:50
I’m afraid (but not really surprised) that I am unable to reproduce this. On my M2 MacBook Pro, with Sonoma 14.6.1, even when I open all six playback simulator windows and have them all playing, the % GPU is 0.0. There must be something strange going on on your machine. You may want to try other JVM versions or vendors, perhaps Amazon Corretto 17 has issues with the M3. (You can do that by installing, say, a recent Azul or OpenJDK distribution, and using the cross-platform Jar distribution of BLT.)

**Comment by brunchboy** [comment] 2024-08-15 03:50
<img width="818" alt="Screenshot 2024-08-14 at 22 46 36" src="https://github.com/user-attachments/assets/bf660faa-b4b8-412a-8727-b0b4bdc7711b">

**Comment by brunchboy** [comment] 2024-08-15 03:51
If you had any custom expressions running, then I would also try looking at those. Barring additional information which allows this to be reproduced, I am going to close it. If you would like more help investigating it, please reach out in the Zulip community.

**Comment by brunchboy** [comment] 2024-08-15 04:16
OK, interesting! Even though the GPU is not used at all when I run Beat Link Trigger from within Emacs, when I use one of the versions that is packaged up as a Mac application, I can see this phenomenon. But there’s absolutely nothing I can do about that. If you happen to know anyone who is interested in and expert at performance analysis of Java applications, and how to tie GPU activity to particular threads and methods, I would definitely appreciate any analysis and suggestions they might be able to contribute. But for now we are just going to have to say, this is an artifact of how the drawing happens. It doesn’t actually prevent anything from working, and as I mentioned above, the shallow playback simulator is not a core feature of BLT, and should be used only rarely when for some reason real player hardware is temporarily unavailable.

Also keep in mind that performance and efficiency are non-goals of this project. It is entirely focused on flexibility and extensibility, allowing people to quickly build integrations that were previously impossible. So I am not going to invest further time on investigating this. If you can, awesome! And either way, I would like to hear more in Zulip.

**Comment by brunchboy** [comment] 2024-08-15 04:22
Oh, and if you do see any different behavior with different Java distributions that would be interesting information as well. As a starting point, when I run it from Emacs, it is using Amazon Corretto 11.0.14.1. This actually makes me suspect it’s the JVM that is the difference.

**Comment by brunchboy** [comment] 2024-08-15 04:36
I really should be in bed, but I did a little more poking around, and this is weird enough that I am going to reopen the issue, and hope you can help investigate it with me.

I switched my default Java to Corretto 17, and still saw 0% GPU attributed to the Java process when I was running it in Emacs. But then I found the GPU history window, and saw that when the Simulator window is open, that does get pinned, even though the OS does not blame the Java process for it. Looking at all processes, sorted by GPU %, I discovered that it was being attributed to the WindowServer process. So somehow when it is run this way, it is not being attributed properly.

I will leave this kicking around on the back burner. It’s not a priority because, as I noted above, the Shallow Playback Simulator is a weak tool for use in unfortunate circumstances, and performance concerns are not the focus of this project. But if we can find a simple way to resolve this, it would be nice. Here is the [simulator source](https://github.com/Deep-Symmetry/beat-link-trigger/blob/main/src/beat_link_trigger/simulator.clj) to help focus your study if you can help.

**Comment by brunchboy** [comment] 2024-08-17 02:02
Now that I have had a little time to poke around I have already verified that this is a real issue, and something I will be able to address myself. The simulator window is updating UI objects far more often than it needs to. That can be cranked down, and some checking of last values used to suppress updates can likely also help. Thanks for reporting this! I will hopefully have a preview build that behaves better available sometime this weekend.

**Closed** 2024-08-17 02:50 UTC
Labels: bug

**Comment by brunchboy** [comment] 2024-08-17 02:52
I just pushed some tweaks that seem to make the UI update behavior of the simulator window vastly more reasonable. I want to download and test the macOS application package once GitHub Actions creates it before I call this truly fixed, but it is looking promising so far.

**Comment by brunchboy** [comment] 2024-08-17 02:57
Sigh… Allen & Heath broke the URL for the Xone:96 Midi Control Overview PDF, so until I fix that and cherry-pick it to all active version branches of the user guide, the preview build won’t be able to complete. Working on that now.

**Comment by brunchboy** [comment] 2024-08-17 03:16
Yes, this is behaving much more reasonably now. I’d appreciate it if you could verify that the [latest preview release](https://github.com/Deep-Symmetry/beat-link-trigger/releases/tag/latest-preview) resolves this issue on your system as well.

**Comment by Firedude1** [comment] 2024-09-10 06:12
Hi! It seems like my GitHub notifications weren't configured right so I completely missed your second round of responses, I'm so sorry!!! Thank you so much for giving this issue so much time, I can confirm that it is now completely fixed in the preview release. 
Thank you again!

**Comment by brunchboy** [comment] 2024-09-10 12:25
It’s rough when our tools betray us like that! 😅 I am glad you didn’t happen to look Sunday when Apple had broken my build process, because you would have found no macOS previews to test with. Thank you for having found my rambling discussion on your own and verifying the fix.

**Comment by Firedude1** [comment] 2024-09-11 17:33
Ah the joys of developing for macos ;)
It's so cool to see a full application written in Clojure, I've never seen it put into practice on the desktop! I'd imagine it can't be fun integrating it into macOS tooling.

**Comment by brunchboy** [comment] 2024-09-12 16:49
Indeed! Things are better now that recent OpenJDK releases have a `jpackage` tool that can create signed packages and disk images with your code and a runtime with a selection of Java modules, but even with that it took me many days of tinkering to figure out how to make it work automatically and securely in my GitHub Actions pipeline, and to fix it from time to time. But it has been well worth it, now I can just push changes and a few minutes later the preview builds are ready for various architectures. In the old days I had to do a lot of finicky manual steps to create and then upload them.

I’m also involved with another project that feeds into Beat Link Trigger, [CoreMidi4J](https://github.com/DerekCook/CoreMidi4J) that is even more fun to build because it involves using Xcode to compile a native library, and linking to that from Java.

**Comment by Firedude1** [comment] 2024-09-18 08:42
That's super sweet!!
