### ISSUE TITLE
couldn't see PLAYING status working

### ISSUE THREAD

**Issue by piotrus04** [Deep-Symmetry/beat-link-trigger#66] opened 2019-01-17 13:57 UTC
### Version of Beat Link Trigger

Version: 0.4.1

### Version of Java

Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

### Version of OS

macOS 10.12.6

### The issue you're experiencing

i only have one CDJ2000 connected to a router, and my computer connected to the router.
When i press the Play button on the CDJ2000 Nexus 2, i couldn't see "playing" in blue color text.
 I could only see 2 (the id of the player i guess) and "Stopped, Master, Track id ... ... ..."
I couldn't understand why the playing status is not refreshing, and so the events triggers are not working...

**Comment by brunchboy** [comment] 2019-01-17 16:09
I’m sorry, there is not nearly enough information here for me to help you. If you can reproduce the problem and include log files and perhaps network traffic captures, and a screen shot of what you are talking about, please do.

**Comment by piotrus04** [comment] 2019-01-17 18:34
Thanks for your answer.
Unfortunately I had the cdj only for one day.
As soon as possible, I 'll try to sniff the Ethernet traffic.
All the best

Pierre
Visualsystem.org

**Comment by brunchboy** [comment] 2019-01-18 02:39
Thank you, I don’t have access to any nxs2 players, so if there is difference in their behavior which is not captured in our current understanding of our protocol, help from someone like you will be the only way to fix it. If you know ahead of time when you might have the player again, I can try to be available for fast turnaround with followup questions. Did you happen to try opening the Player Status window while you were experimenting?

**Comment by piotrus04** [comment] 2019-01-18 14:20
Hi,
Yes, the setup was :

Macosx>>>
Cdj >>>>>-> DHCP router

The firmware cdjnxs2 v1.84

The show status window could open, but only the "BPM" parameter was
refreshed.
Maybe the name too if it is displayed in this window.
But all other parameters were not refreshed, and "empty"

Very strangely, I could in the script windows track the "paused?"
Information to make one trigger depend on this behaviour.
Like a hack, I tried to make a script depending on a "not paused?" But so I
had other problems like the fact that the Nexus trigger very quickly some
"paused?" Status data's when you change the track or select another track.

As soon as I have more information from Wireshark or something like that, I
ll send to you more accurate information.

All the best and thank you very much for your answers!

Pierre

**Comment by brunchboy** [comment] 2019-02-18 03:39
Since there has been no new information, and I have not heard any other issues similar to this, I am closing this one. If you are able to reproduce the problem (especially with the latest 0.5.0 preview, or likely the 0.5.0 final release will be out by the time you come back to this), then please open a new issue with the specific details, logs, and network captures. Thanks!

**Closed by brunchboy** 2019-02-18 03:39 UTC
Labels: awaiting details

**Comment by piotrus04** [comment] 2019-02-18 09:28
Thanks James, sorry to not have been so responsive. I was full time working
on similar projects. I sincerely come back to the forum if I get a cdj2000
to my office.
All the best
Pierre

Pierre Gufflet
visualsystem.org
