### ISSUE TITLE
Support Multilingual title and artist on Player Status window

### ISSUE THREAD

**Issue by procx** [Deep-Symmetry/beat-link-trigger#107] opened 2020-08-07 06:03 UTC
In the Player Status window of the beat link trigger, the title and artist fields do not currently support multiple languages and characters are either not displayed or appear garbled.

I'd like you to support multiple languages in these fields so that they will be displayed correctly.

You may be able to display them if you update the font files in /resources/fonts/ to support multiple languages. You may need to modify the code a little.

Thank you for your consideration.

**Comment by brunchboy** [comment] 2020-08-07 16:19
Hi, @procx, thanks for the report. I have not run into this with any of the languages I have tried; could you please submit some sample text that can reproduce the problem? Also, this sounds like a great task for you (or another person who has not yet contributed code to the project) to attempt. Please submit a pull request if you find fonts that work well!

**Comment by brunchboy** [comment] 2020-08-07 16:26
Also, could you please fill out all the information that was present in the issue template? There’s a good reason I ask for it; I need to know what exact reason of Beat Link Trigger you are testing with, because this issue may have already been addressed in the preview release (see the “Fixed” section of the Unreleased top of the [change log](https://github.com/Deep-Symmetry/beat-link-trigger/blob/master/CHANGELOG.md). If your track metadata was coming via Crate Digger (which is usually the way things work), they were likely corrupted by an error in how Unicode was being interpreted which has been fixed in the preview release, and which has nothing to do with the fonts.

**Comment by brunchboy** [comment] 2020-08-07 16:30
Ah, of course since you started with the feature request template, it doesn’t ask all those questions. This makes it look like I should ask for what version you are currently running even when you are asking for a feature, in case it is already implemented in the preview release. 😄 In any case I look forward to learning what you are running, and whether the snapshot build solves this for you.

**Comment by procx** [comment] 2020-08-07 17:21
Hi @brunchboy, thank you for your reply, and sorry for not fill out in the issue template. For details as below:

**Describe the bug**
In the Player Status window of the beat link trigger, the title and artist fields do not currently support multiple languages and characters are not shown.

**To Reproduce**
1. load a track having multilingual title or artist in a file name or ID3 tag to the CDJ.
2. multilingual title and/or artist is not shown on the Player Status window.

**Expected behavior**
1. multilingual title and artist is shown correctly on the Player Status window.

**Screenshots**
No screenshots, sorry.

**Exceptions and Stack Traces**
No exceptions and stack traces.

**Desktop (please complete the following information):**
 - Beat Link Triger Version: Version 0.6.2 Sun May 10 22:03:41 UTC 2020
 - Java Version: 14, OpenJDK 64-Bit Server VM, Oracle Corporation
 - OS: macOS Catalina 10.15.6

**Additional context**
sample text that can reproduce.
This sample is Japanese text.
 - title: 涼宮ハルヒの憂鬱 ハレ晴レユカイ
 - artist: 平野綾

This sample is Korean (Hangeul).
 - title: 환상동화
 - artist: 아이즈원

This sample is Chinese.
 - title: 阳光小鬼头
 - artist; 乐华少年

My enhancement request seems to be exactly what is described in the unreleased "Fixed" section.
Thank you for your consideration.

**Comment by brunchboy** [comment] 2020-08-07 17:50
No apologies necessary! You did fill out the correct template for the category of issue that you opened, I just previously did not include a question about the BLT version in that template. My mistake, not yours, and I have fixed it.

Yes, it looks like the issue you have run into is exactly the one that was fixed in the Beat Link and Crate Digger libraries which are part of the preview release. Could you please test with that and let me know? This may be enough of a reason to go ahead and release it, although I have wanted to wait for more people to validate the OBS features first. You can run the preview release for as long as you want, and eventually it will be replaced by a new formal release. You can find it at the top of the Releases page, or here: https://github.com/Deep-Symmetry/beat-link-trigger/releases/tag/v0.6.3-SNAPSHOT

**Comment by procx** [comment] 2020-08-07 18:10
Thank you for your 0.6.3-SNAPSHOT release information!
I'm going to try this version out for testing. And I'll report back to you with the results.
(Please give me some time to report the test results as it is difficult to set up the test environment due to circumstances.)

**Comment by brunchboy** [comment] 2020-08-07 18:31
No rush, thanks for anything you can discover when you have time.

**Comment by procx** [comment] 2020-08-11 06:11
Hi @brunchboy

I was able to test 0.6.3-SNAPSHOT yesterday under the following environment. As a result, the Artist and Title fields are not displayed in multiple languages.

- DJ Mixer: Pioneer DJ DJM-900NXS2
- CDJ: Pioneer DJ CDJ-2000NXS x 2
- Beat-Link-Trigger: 0.6.3-SNAPSHOT-59-0x781b Fri Aug 07 16:35:19 UTC 2020

The cause of the problem is clear: the font used by beat-link-trigger is an European font, and the font files do not contain Chinese, Japanese and Korean (i.e. CJK) character fonts.
I believe that even if I process UNICODE correctly, no characters will be displayed because they are not present in the font file.

As an alternative font, I suggest source-hans-sans. The copyright is also the SIL Open Font License, Version 1.1, so it won't be a problem. Additionally, the font project is hosted on GitHub.
https://github.com/adobe-fonts/source-han-sans/

Thank you for your consideration.

Screenshots as following:
- beat-link-trigger version:
<img width="512" alt="BLT Version 0 6 3-SNAPSHOT-59-0x781b" src="https://user-images.githubusercontent.com/6748166/89863018-1df76380-dbe4-11ea-973c-b0077dc81fe6.png">

- not shown in Korean
<img width="615" alt="少女時代, エイプリル(ハングル表示されず)" src="https://user-images.githubusercontent.com/6748166/89863068-3ebfb900-dbe4-11ea-85ed-15d277108670.png">

- expected result in Korean
<img width="615" alt="少女時代, エイプリル(not shown in Korean)" src="https://user-images.githubusercontent.com/6748166/89863097-5434e300-dbe4-11ea-8b72-04aa05cb73c1.png">

- not shown in Japanese
<img width="615" alt="東方神起, 夏の日(日本語表示されず)" src="https://user-images.githubusercontent.com/6748166/89863168-87777200-dbe4-11ea-9d6f-b73e0f9ec8de.png">

- expected result in Japanese
<img width="615" alt="東方神起, 夏の日(not shown in Japanese)" src="https://user-images.githubusercontent.com/6748166/89863200-98c07e80-dbe4-11ea-9dcc-5008fec6af9a.png">

**Comment by brunchboy** [comment] 2020-08-11 16:13
Thanks for the thorough report! Are you willing to try installing this font and seeing if it solves the problem, and submitting a pull request with the changes? I’d really like to increase the number of people contributing code and resources to the project, and this seems like a nice, isolated way to start. I’d be happy to give pointers if you try and get stuck.

**Comment by procx** [comment] 2020-08-11 17:03
I am going to try your suggestions. However, I'm new to writing Java and Clojure programs, so I hope you won't expect too much from me.

**Comment by brunchboy** [comment] 2020-08-11 17:05
That’s wonderful! Thanks for being game to try this, and I am very happy to help. If you manage to get it working then the pull request will reflect your contribution, but even if you decide it is too much of a hassle and have me do it instead, I will credit you in the release notes for all the research you have already contributed.

**Comment by brunchboy** [comment] 2020-08-11 17:11
As a pointer to get you started, you will want to put the font (and any required license file) in a folder inside here: https://github.com/Deep-Symmetry/beat-link-trigger/tree/master/resources/fonts

Then you will want to add code in `load-fonts` to load any font files you added: https://github.com/Deep-Symmetry/beat-link-trigger/blob/163a46c42403cdeeefc212496a87320e29eef664/src/beat_link_trigger/util.clj#L260-L276  (look at lines like 269 and 270 as examples of what you will add).

Then you will want to add a new keyword to `get-display-font` allowing other code to easily access your new font: https://github.com/Deep-Symmetry/beat-link-trigger/blob/163a46c42403cdeeefc212496a87320e29eef664/src/beat_link_trigger/util.clj#L307-L323

And then finally, in the code that creates the artist and title labels, you will want to use your new font keyword: https://github.com/Deep-Symmetry/beat-link-trigger/blob/163a46c42403cdeeefc212496a87320e29eef664/src/beat_link_trigger/players.clj#L759-L761

**Comment by procx** [comment] 2020-08-11 17:14
Thank you for your information for getting started!

**Comment by brunchboy** [comment] 2020-08-11 17:18
My pleasure! Of course I realize now I skipped the part about how you can build and run your own fork, but hopefully the Contributing page will take care of that. If you run into any snags, please let me know ways it could be improved: https://github.com/Deep-Symmetry/beat-link-trigger/blob/master/CONTRIBUTING.md

**Comment by procx** [comment] 2020-08-12 13:57
I follow the CONTRIBUTING.md documentation to install the necessary tools, run the lein repl command in the CLI, and now I get an error that the (start true) command fails to resolve symbols, even though I am prompted. Am I missing some packages or runtime on my PC?

screenshot as following:

![lein repl (start true) Unnable to resolve symbol](https://user-images.githubusercontent.com/6748166/90023767-11abfd00-dcef-11ea-8855-8598bf80590f.png)

**Comment by brunchboy** [comment] 2020-08-12 15:06
Unfortunately, I can’t be much help with issues around Windows development, as I don’t do it. However, an error like this usually means there was a preceding error which prevented the proper compilation and loading of the namespace in which you are trying to invoke the `start` function (in this case, `beat-link-trigger.core`. And indeed it looks like I see the very last line of a stack trace in the screen shot you posted above. The details of what went wrong were reported in the lines just off the top of the screen (probably a great many of them). If you can share the entirety of that, I might be able to help figure out what is going wrong.

**Comment by brunchboy** [comment] 2020-08-12 15:08
But it does look like you are very close to having it working! 😄

**Comment by procx** [comment] 2020-08-12 15:22
Thanks for the support.
First off, I'm trying to develop on Macbook Pro macOS Catalina 10.15.6, not Windows.
Then I followed the stack trace and found that "org/deepsymmetry/libcarabiner/Runner has been compiled by a more recent version of the Java Runtime (class file version 53.0), I found an error message that says "This version of the Java Runtime only recognizes class file versions up to 52.0". It seems that the Java Runtime installed in my MBP is a bit old. I will update to a more recent version and try again.

screenshot as follows:

![libcarabiner error](https://user-images.githubusercontent.com/6748166/90034000-0eb70980-dcfb-11ea-82ee-7d214a5803f2.png)

**Comment by brunchboy** [comment] 2020-08-12 15:28
Oh, thanks! When you said “PC” I read “Windows PC”, sorry! 😆 I use Catalina and Mojave as well.

But yes, you need to be using a current Java distribution. I recommend Amazon Corretto. Most of Beat Link Trigger is built against Corretto 11, which is the current long-term-support version, and that should serve you fine.

**Comment by brunchboy** [comment] 2020-08-12 15:29
Here’s the download link for Amazon Corretto 11: https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html

**Comment by brunchboy** [comment] 2020-08-12 15:37
Based on those class file version numbers, you were running Java 8, and libcarabiner requires Java 9 or later.
https://stackoverflow.com/questions/9170832/list-of-java-class-file-format-major-version-numbers

**Comment by procx** [comment] 2020-08-12 15:38
The UI is up correctly! Thank you for your support!!

**Comment by brunchboy** [comment] 2020-08-12 15:49
And thank you for digging into this! I updated the contributing page to be more explicit about Java versions and how to find them.

**Comment by procx** [comment] 2020-08-13 00:55
Hi, @brunchboy 
I fixed code for multilingual, but how do I test the code? Do I actually need a DJM, CDJ and PRO DJ LINK to test it?

**Comment by brunchboy** [comment] 2020-08-13 02:55
No DJM is needed, but you do need to connect via Pro DJ Link to a CDJ. How did you find the problem in the first place?

**Comment by brunchboy** [comment] 2020-08-13 03:11
If you just want to test your font, you could just create a window, put a label in it configured to use your new font, and set the text to one of your values that did not work before, but if you are not used to coding in Java Swing, it would probably be a lot easier to connect a CDJ.

**Comment by procx** [comment] 2020-08-13 03:52
I discovered this issue when I was actually connecting DJM, CDJ, and my MBP with beat-link-trigger installed, via PRO DJ LINK.

So that means I have to test in the same environment. It would have been nice to have an easy way to test the Player Status window display, but that's just the way it is.

As I explained when tackling this issue, I'm new to Java/Clojure. So I decided to test in the same environment. It is a bit difficult to prepare, but please give me some time to test it.

Originally I thought the best solution would be to allow users to optionally select the font to be used to display the Player Status window, but this is beyond my technical ability. I'll have to wait for future improvements.

**Comment by brunchboy** [comment] 2020-08-13 03:57
There’s no rush! I appreciate everything you are doing here. I have an XDJ-XZ at home, and a nexus 2000 setup (two CDJs and a DJM) in storage, so it’s pretty easy for me to test. If you would like me to clone your repo and try with some of the text you posted above, I could do that. But I am also happy to wait for you to have time.

Letting people pick a font is probably a direction I wouldn’t want to go either. I try to be pretty focused and minimal in Beat Link Trigger, and that would open a lot of complexity. I hope we can find a single font that works for all languages and looks decent.

**Comment by procx** [comment] 2020-08-13 06:39
I've just pushed the modified code into the Multilingual-Support branch in my project that I forked from your project.
https://github.com/procx/beat-link-trigger/tree/Multilingual-Support

I've uploaded the 2 files with the file name and ID3 tag included the multilingual artist and title so you can download them and test if the Player Status window appears as you expect it to.

If you can attach screenshots of the Player Status window here, I will check if it appears as expected.

file 1: with Korean characters
- artist: 에이프릴 (APRIL)
- title: 파랑새 (The Blue Bird)
- URL: https://drive.google.com/file/d/1QJDrVsuehBZ9b1pjWzZoFBjDhr9QGMxZ/view?usp=sharing

file 2: with Japanese characters
- artist: 椎名林檎
- title: 歌舞伎町の女王
- URL: https://drive.google.com/file/d/1qJgE87ei-gjpvpEdl_H_Mr5Mrq58xLbQ/view?usp=sharing

**Comment by brunchboy** [comment] 2020-08-13 13:10
Thank you! I will conduct those tests after work, or (if I have time) at lunch. In the mean time I threw together something you can try at the REPL. Evaluating the following code creates a window with that text in it, using the font I am already using. Strangely, when I try this, the strings show correctly. I don’t understand why they are not in the player status window, perhaps because of the color I am using? But you can perhaps experiment with those variations, or try swapping in your font and see if it behaves any differently:

```clojure
(seesaw/invoke-now
 (let [title-font  (util/get-display-font :bitter java.awt.Font/ITALIC 14)
       artist-font (util/get-display-font :bitter java.awt.Font/BOLD 12)
       labels      [(seesaw/label "Here are some sample labels:")
                    (seesaw/label :text "에이프릴 (APRIL)" :font artist-font)
                    (seesaw/label :text "파랑새 (The Blue Bird)" :font title-font)
                    (seesaw/label :text "椎名林檎" :font artist-font)
                    (seesaw/label :text "歌舞伎町の女王" :font title-font)]
       panel       (seesaw/vertical-panel :items labels)
       frame       (seesaw/frame :title "Font tester"
                                 :content panel
                                 :on-close :dispose)]
   (seesaw/pack! frame)
   (seesaw/show! frame)))
```
<img width="296" alt="Screen Shot 2020-08-13 at 08 09 55" src="https://user-images.githubusercontent.com/2228869/90138301-6de93e00-dd3c-11ea-8f15-ce7a97fe016d.png">

**Comment by brunchboy** [comment] 2020-08-13 13:30
Ah, no! I messed up. I had not called `(util/load-fonts)` and so it was using the default system font. I didn’t initially notice that the text didn’t look the same as in Player Status. OK, after calling that your problem is reproduced:

<img width="296" alt="Screen Shot 2020-08-13 at 08 27 16" src="https://user-images.githubusercontent.com/2228869/90140146-ecdf7600-dd3e-11ea-9642-6e2044ab406a.png">

So if you would like to test with your own font before I have a chance to experiment with your repo and the files you shared, you can just change the `:bitter` keyword in the my sample code above that sets up the font variables to the one you added, it will be a valid test. (Just remember to call `(util/load-fonts)` at least once before running the tests.)

**Comment by procx** [comment] 2020-08-13 16:53
Thanks for the minimal PoC that reproduces the problem. I'll test this PoC later if it is shown as expected in SourceHanSansK font.

**Comment by brunchboy** [comment] 2020-08-13 17:48
All right! It turns out that I have a meeting over lunch, so I won’t be able to get around to testing your branch until after work. Also that font name made me a bit concerned, so I looked at it, and it appears to be a sans-serif font. The Bitter font that I am currently using is intentionally a serif font, is there a serif font we could use in order to preserve the typography of the window? If not, then we might as well just use the built-in Java default font, which supports many Unicode planes (it sounds like this font only has Korean, perhaps?)

Ideally I would like to find a font that looks similar to Bitter but which supports the full Unicode space and all language families.

**Comment by procx** [comment] 2020-08-13 18:10
There is a source-han-serif font.
https://github.com/adobe-fonts/source-han-serif

Ideally, we should use True Type font files that contain all the characters, but there are too many characters, so the font files are separated by language and weight. I think the program should detect the character codes and use a font that is suitable for Chinese, Japanese, and Korean. However, that would be a very painful task, so I have chosen a Korean font that includes some Japanese and Chinese. Alternatively, I haven't checked if this is possible in Java/Clojure yet, but there may be a way to let the system (OS) choose the best font for it.

**Comment by brunchboy** [comment] 2020-08-13 18:24
I don’t think there is any way to do that, although it may be that if we include all the font files, then the system chooses the correct file for the language when you ask for them by family name. It may also be best and simplest to just use the default system fonts, which seem to already do this. We can do some experimentation and decide what looks and works best. I agree that working in all languages is more important than whatever typographic look I was aiming for. 😄

**Comment by brunchboy** [comment] 2020-08-13 18:26
Also, we can’t pick font files ourselves based on characters, because we are using a single label object, which might contain characters from multiple language families, and the label can only be assigned one font object.

**Comment by procx** [comment] 2020-08-13 18:48
I've just pushed the code and font files using the SourceHanSerifK font to my repository.
https://github.com/procx/beat-link-trigger/tree/Multilingual-Support

It's 3:45 a.m. in Tokyo right now and I have to go to bed for work tomorrow, so I'll try to test your PoC tomorrow.

**Comment by brunchboy** [comment] 2020-08-13 18:52
Good night, thanks again for all your work and thought on this.

**Comment by procx** [comment] 2020-08-14 01:28
Good news. The following code showed up as expected. 
(However, the SourceSanSerif font series do not have italics. so, should I look for another font that has italics?)

```clojure
(seesaw/invoke-now
  (util/load-fonts)
  (let [title-font   (util/get-display-font :sourcehanserifk java.awt.Font/ITALIC 14)
          artist-font (util/get-display-font :sourcehanserifk java.awt.Font/BOLD 12)
          labels        [(seesaw/label "Here are some sample labels:")
                             (seesaw/label :text "에이프릴 (APRIL)" :font artist-font)
                             (seesaw/label :text "파랑새 (The Blue Bird)" :font title-font)
                             (seesaw/label :text "椎名林檎" :font artist-font)
                             (seesaw/label :text "歌舞伎町の女王" :font title-font)]
       panel           (seesaw/vertical-panel :items labels)
       frame          (seesaw/frame :title "Font tester"
                                                     :content panel
                                                     :on-close :dispose)]
  (seesaw/pack! frame)
  (seesaw/show! frame)))
```

screenshot:

<img width="296" alt="スクリーンショット 2020-08-14 10 10 29" src="https://user-images.githubusercontent.com/6748166/90201808-e91f2280-de16-11ea-8337-df2dfc904d97.png">

**Comment by brunchboy** [comment] 2020-08-14 04:53
That’s encouraging. I’m sorry I wasn’t able to get to trying your branch with my Pioneer equipment tonight, it’s been a busy week at work, and I had complicated cooking to do afterwards, so I am afraid I won’t be able to work on Beat Link Trigger until this weekend. But how do you feel about this approach? We could simply not include a new font, and use the built-in multilingual serif font, which supports all the standard variations (bold and italic) like so:

```clojure
(seesaw/invoke-now
 (let [title-font  (java.awt.Font. "Serif" java.awt.Font/ITALIC 14)
       artist-font (java.awt.Font. "Serif" java.awt.Font/BOLD 12)
       labels      [(seesaw/label "Here are some sample labels:")
                    (seesaw/label :text "에이프릴 (APRIL)" :font artist-font)
                    (seesaw/label :text "파랑새 (The Blue Bird)" :font title-font)
                    (seesaw/label :text "椎名林檎" :font artist-font)
                    (seesaw/label :text "歌舞伎町の女王" :font title-font)
                    (seesaw/label :text "YHBOYS 乐华少年" :font artist-font)
                    (seesaw/label :text "阳光小鬼头" :font title-font)]
       panel       (seesaw/vertical-panel :items labels)
       frame       (seesaw/frame :title "Font tester"
                                 :content panel
                                 :on-close :dispose)]
   (seesaw/pack! frame)
   (seesaw/show! frame)))
```

This results in the following window:

<img width="296" alt="Screen Shot 2020-08-13 at 23 49 21" src="https://user-images.githubusercontent.com/2228869/90214936-c150a000-ddbf-11ea-8aac-09a565982b7a.png">

If you think that seems readable enough, we could change the code in `players.clj` to use the same `Font` constructors I used in the example above instead of calling `util/get-display-font`, and save space in the jar file by not embedding any font for this purpose. (I don’t think I am using Bitter anywhere else, so if we can confirm that, we could even remove that file and the keyword/code that uses it).

**Comment by brunchboy** [comment] 2020-08-14 04:55
Another thing that we want to double-check is that the code that draws cue comments is using a standard font (or, if not, that it is using one that supports Asian and other language families). We will need to look at the Beat Link code that draws waveforms (and perhaps the Beat Link Trigger code that configures it, I don’t remember right now if I exposed a font configuration property or not).

**Comment by procx** [comment] 2020-08-14 05:17
I think your approach to this issue of using the built-in multilingual serif font is correct. I think this font is easy enough to read.
I'll also check out the fonts used to draw cue comments and waveforms.

**Comment by procx** [comment] 2020-08-14 07:16
I checked the font used to draw the cue comments and waveforms. `:font` and `:bitter` were not used in the code to draw cue comments and waveforms. In other words, I assume that this indicates that standard fonts are used to draw cue comments and waveforms.

**Comment by brunchboy** [comment] 2020-08-14 16:36
All right, let’s proceed in that direction. I see two places that use the Bitter font at the moment, the Player Status window that you are already changing, and also the Show interface, https://github.com/Deep-Symmetry/beat-link-trigger/blob/6173c97eb019ae65e13ad1cb8e2881e8fdb75ce6/src/beat_link_trigger/show.clj#L3400-L3409

So in both of these files, we will want to replace expressions like `(util/get-display-font :bitter Font/ITALIC 14)` with the more multilingual-friendly version `(Font. "serif" Font/ITALIC 14)`. (This replaces an invocation of my own Clojure font-lookup function with a standard Java `Font` object constructor, to use the built-in serif font that supports all these language families.)

Then we can completely remove the `resources/fonts/Bitter` folder, and reduce the executable size. (We’ll also want to remove the directory you added for the alternate font that we were considering using.)

The default font used for drawing cue comments is determined by code in the Beat Link library, a separate project that does most of the work for Beat Link Trigger: https://github.com/Deep-Symmetry/beat-link/blob/d610b948db1ab3958026c06608fb2630152d5865/src/main/java/org/deepsymmetry/beatlink/data/WaveformDetailComponent.java#L110-L115

Because that uses a standard system font, and Beat Link Trigger does not change it by calling `setLabelFont` anywhere, we should be safe. I’ll still test that by using some of your sample text in a few cue comments, but I think we are getting close to a good solution. Thanks again for opening this issue and all your work towards solving it, I look forward to a pull request when you have a chance to try these things, and will have time to help test more this weekend.

**Comment by procx** [comment] 2020-08-14 18:28
I have some schedules in this weekend, so I may not be able to work on it. When I get time to work on it, I'll give it a try.

**Comment by procx** [comment] 2020-08-18 00:40
I was not able to work on it yesterday because of a troublesome job. 

I can finally get to work on beat-link-trigger. As instructed, I removed the Bitter font from the resource directory, removed the :bitter directive from the source code players.clj, show.clj and util.clj, and pushed it to my forked project.

https://github.com/procx/beat-link-trigger/tree/Multilingual-Support

**Comment by brunchboy** [comment] 2020-08-18 01:14
All right, I will clone it now and give it a look and a try, but it is sounding like it’s time for you to open a pull request to get your changes merged in.

And I feel like even a troublesome job is a good thing to have in today’s world. 😄

**Comment by procx** [comment] 2020-08-18 01:27
I haven't finished testing the modified code yet, so I'll submit a pull request when I get the expected results.

**Comment by brunchboy** [comment] 2020-08-18 01:30
That makes sense! There are a couple of problems, which are very difficult to discover without being able to go online with a CDJ, so I’ll let you know about those. One way to find one of them is to create a show file. I think I forgot to mention one place where we need to make changes, which is in `beat-link-trigger.util/load-fonts  util.clj:  274`, it is still trying to load the Bitter font. These three entries need to be removed from the list of files to load:

https://github.com/procx/beat-link-trigger/blob/00d59394df747a1c98e6c6a1980ce7ce601e3a51/src/beat_link_trigger/util.clj#L271-L273

**Comment by brunchboy** [comment] 2020-08-18 01:36
The other issue is that you can’t use `util/get-display-font` to access the system standard fonts—I wrote that to provide access to the custom fonts I embedded in the program. I showed the alternate code you need to use instead above, although I am not surprised that detail got lost in all the talking I have been doing. I’ll add a comment on your commit about this as well, but in the places you code like this:

```clojure
(util/get-display-font "serif" Font/BOLD 12)
```

it needs to be replaced with code like this:

```clojure
(Font. "serif" Font/BOLD 12)
```

Sorry about the complexity, and thanks again for all you are doing on this.

**Comment by brunchboy** [comment] 2020-09-01 03:52
It seems like things have come up (as happens a lot to me this year), but I do hope you will find time to put together this pull request one day, it will be a nice fix.

**Comment by procx** [comment] 2020-09-02 09:55
Sorry for the delay in responding to you. I've had a lot of very hard and troublesome work and I needed some rest.  Please give me a little more time until I can play with beat-link-trigger again.

**Comment by brunchboy** [comment] 2020-09-02 16:10
Of course! I’m sorry to hear about the stress, and look forward to someday you having time for this to be enjoyable to proceed with.

**Comment by brunchboy** [comment] 2020-09-12 05:13
Thank you, your fix has been merged. In the release notes, would you like to be credited as @procx or @dkatoh-nict ? And would you like a full name to be listed?

**Comment by procx** [comment] 2020-09-12 06:45
Thank you for merging my pull request!! great work!!

> Thank you, your fix has been merged. In the release notes, would you like to be credited as @procx or @dkatoh-nict ? And would you like a full name to be listed?

please credit as "@procx (xcorp)". :)

**Comment by brunchboy** [comment] 2020-09-12 20:04
All right, the change log is updated. 😄

**Closed** 2020-09-12 20:04 UTC
Labels: enhancement, help wanted
