### ISSUE TITLE
Device slot taken over by unknown "invader"

### ISSUE THREAD

**Issue by CKunhardt** [Deep-Symmetry/beat-link-trigger#133] opened 2022-03-12 03:21 UTC
**Describe the bug**

I'm at a party at which beat-link-trigger was integral to my lighting setup right now, and I'm unable to go online with the program.

BLT actually does go on, and is assigned to Player 7, but the triggers all still show offline and my Carabiner instance refuses to enter Sync mode. Upon looking at the logs, I see my BLT goes online successfully but then is instantly invaded by "invader at address 0.0.0.0:ffff:a9fe:7efa," and after a short battle of sending "device number defense packets" to the invader, my poor BLT instance gives up and, despite a few "Mixer confirmed device assignment" messages, eventually reports "Another device has claimed it owns our device number, shutting down," after which is receives "device number defense messages for device 7 when we are not running."

Online shows device 7 and checked still, but all my triggers show "Offline." When I try to toggle online, it goes off, but on toggling back on the program restarts itself and is still offline when it comes back. Closing and reopening the program gets the Network -> Online? to show Player 7 again, but still no actual connectivity.

**To Reproduce**

I can send logs etc tomorrow, but we have 4 CDJ 2000nxs2s plugged into an 8 port switch, plus my ethernet run, which goes into a dedicated usb adaptor on my computer. Same thing if directly into my computer. No actual internet in venue, so no concerns there.

**Expected behavior**

**Screenshots**

**Exceptions and Stack Traces**
If possible, copy and paste or attach as much of the log file as needed to show where things were going wrong or not working as expected.

**Desktop (please complete the following information):**
 - Beat Link Triger Version: 7.0.0
 - Java Version: 17.0.2
 - OS: win 10 pro

**Additional context**
Add any other context about the problem here. The more you can share, the more likely we are to be able to help.

I can provide more details as needed tomorrow.

**Comment by brunchboy** [comment] 2022-03-13 01:51
Hello, Clinton, I am sorry to hear this happened. I’ve never heard of anything like it, so I hope you can figure out what is happening on your system. You may want to ask the [user community on Zulip](https://deep-symmetry.zulipchat.com/login/) to see if you can find other people on Windows who might have ideas of what to look at.

Questions that immediately come to my mind are, what other software might be running on your system that could be sending those packets? Also, what is up with that address? Is it an IPv6 address? I have never seen DJ Link traffic on an IPv6 network. It might be worth trying turning off IPv6 on the interface you are using to talk to the players if you have any way of doing that. Although it doesn’t look like any IPv6 address format I have seen, it seems more like an IPv4 shorthand for “any address on the local machine” followed by a bunch of hex digits, and I can’t understand how you could even be receiving traffic from such an address. But alas, I have zero Windows networking experience, so I am not going to be able to help much in understanding this.

Another possibility might be some kind of network loop, in which the packets BLT is sending out are somehow being echoed back to itself, so it sees a reflection of itself as an invader, from which it tries to defend its device allocation. A windows networking expert might be able to help explore this concept, if you can find one. @Kevinnns is the person I would turn to in such a situation myself, but I can’t speak to his availability or interest.

What it may come down to though, is installing [Wireshark](https://www.wireshark.org) and getting familiar with the protocol and packets, and studying what is happening, and tracking it down. The device number defense packets mentioned in the log are described [here](https://djl-analysis.deepsymmetry.org/djl-analysis/startup.html#_channel_conflicts) and that page explains the entire startup / going online process.

Please let me know if you make any headway in figuring this out, so we can at least add it to the troubleshooting page to help others who may encounter it in the future. If you have questions about the protocol analysis document, the Zulip community is probably the best place to ask them.

**Comment by brunchboy** [comment] 2022-03-13 02:10
The more I think about it, the more strongly I believe that the probable cause of the problem is that through some physical or logical network misconfiguration, BLT’s [device announcement packets](https://djl-analysis.deepsymmetry.org/djl-analysis/startup.html#cdj-startup) were being routed back and delivered to itself, and so it tried to communicate with itself as a different device on the network. Seeing the full logs and packet captures could certainly help confirm that, but the underlying fix would be to eliminate that network loop at the operating system or physical connection level. I am curious to hear if Kevin agrees, should he find time to comment.

**Comment by CKunhardt** [comment] 2022-03-13 21:44
Thanks for the reply! I agree, the address looked super odd to me. One thing that comes to mind from what you mentioned is, for running sACN/ArtNet between a few lighting programs on this computer, I've enabled Windows' built-in network loopback interface -- check out the Microsoft documentation [here](https://docs.microsoft.com/en-us/troubleshoot/windows-server/deployment/microsoft-loopback-adapter-rename) if you're curious. This is a pretty essential part of getting a few programs in my setup to work with each other on the same machine, as lighting protocols such as these won't operate on 127.0.0.1 

I'll try plugging into some CDJs again and disabling the loopback adaptor to see if that fixes the issue; it sounds like that's probably the issue. Is there some way to disable BLT from listening on certain interfaces?

**Comment by brunchboy** [comment] 2022-03-13 22:28
Yes, I think we’ve found the problem. No, there isn’t any way to avoid BLT getting confused by traffic coming on particular networks, unless you fork the [beat-link](https://github.com/Deep-Symmetry/beat-link) library and add such a feature to the various listener classes that receive network multicast packets, and then build a version of BLT that embeds your fork, and add startup expressions to configure it that way.

But I doubt that would be a good use of your time: the DJ Link protocol is just not going to work reliably in a network environment that includes loops. As Kevin suggested in the Troubleshooting suggestion of the BLT user guide, it’s best to keep your DJ equipment on a [separate network](https://blt-guide.deepsymmetry.org/beat-link-trigger/7.0/readme#_use_a_separate_network_for_your_dj_gear). If you need to be using software on your laptop that requires this loopback interface, I think that means you should move BLT itself off your laptop, for example onto a Raspberry Pi that you could put on the DJ Link network, and control over VNC.

**Comment by brunchboy** [comment] 2022-04-05 04:48
If there’s nothing new to investigate here, we should close this issue.

**Comment by CKunhardt** [comment] 2022-04-05 14:13
Thanks for the help! Fine by me to close out.

**Comment by brunchboy** [comment] 2023-02-26 20:02
This seems to be happening always in Windows 10 and 11 with the latest preview builds of BLT 7.0.2, which have upgraded the embedded OpenJDK to version 17, so I am reopening this. We have a theory of how we might be able to fix it.

**Comment by CKunhardt** [comment] 2023-02-26 20:07
FYI, my solution to this so far has been to use a small router to create a intranet that I can host everything on. Have to disable the loopback interface every time I want to use BLT, but it works great when I do.

**Comment by brunchboy** [comment] 2023-02-26 20:15
I hope you will not need to do that any more, @CKunhardt! I have just built a new version of the preview release of BLT 7.0.2 which configures the Windows installer to tell Java to not use IPv6, which is the addresses from which you were seeing “rogue traffic” (and which CDJs do not use). If you have a chance sometime, could you [download it](https://github.com/Deep-Symmetry/beat-link-trigger/releases/tag/v7.0.2-SNAPSHOT) and see if it solves the problem for you?

**Comment by brunchboy** [comment] 2023-02-27 15:59
Maddix reports that the 7.0.2 preview resolves his issues with this; I am curious to hear if it does that for CKunhardt as well. But there are other serious problems with cue timing in the preview at the moment, so it is not ready for anything other than testing that.

**Comment by brunchboy** [comment] 2023-02-28 05:35
All right, @CKunhardt, I have fixed the cue timing problems, so I’d love to know, when you have a chance to try it, whether the latest 7.0.2 preview build removes your need to fiddle with the loopback interface.

**Comment by brunchboy** [comment] 2023-03-06 15:36
The previews are now building as 7.1.0, and contain several other important fixes. I am leaving this issue open for a while in the hopes of hearing feedback from @CKunhardt as to whether these builds remove his need to fiddle with his loopback interfaces.

**Comment by CKunhardt** [comment] 2023-03-22 18:24
@brunchboy Thanks for waiting for me -- just gave it a test and it's working smoother than ever right out the box! Great work, and very much appreciate the support.

**Closed** 2023-03-22 22:58 UTC
