### ISSUE TITLE
Loading a track on a player doesn't work for XDJ-XZ

### ISSUE THREAD

**Issue by christophdebaene** [Deep-Symmetry/beat-link-trigger#91] opened 2020-01-11 02:05 UTC
### Version of Beat Link Trigger

Version: 0.6.1-SNAPSHOT-92-0xfdf5

### Version of Java

11.0.5, OpenJDK 64-Bit Server VM,

### Version of OS

Windows 10

### The issue you're experiencing

I am using the Pioneer XDJ-XZ with a USB Stick.
Everything works fine, the player status and browsing through the tracks, but loading a track on a player doesn't do anything.

**Comment by brunchboy** [comment] 2020-01-11 04:37
Interesting. Have you verified whether that works when you do it from rekordbox? If so, could you take a Wireshark packet capture of the packets from rekordbox that do work, and the packets from Beat Link Trigger that don’t?

It may simply be that the XDJ-XZ does not support this feature. Unless someone sends me one, I will be totally reliant on your ability to analyze what is happening on your network, though.

**Comment by brunchboy** [comment] 2020-01-11 05:21
It wouldn’t surprise me if Pioneer just never implemented support for this. The only thing they use these messages for, that I am aware of, is when rekordbox tells players to load tracks from its own collection. That CDJs are also capable of being told to load tracks from each other is not documented, it’s just a cool fact. In this case, the XDJ developers may not have even been aware of that feature, and would probably never thought of implementing it.

**Comment by christophdebaene** [comment] 2020-02-02 18:24
Can it also be analyzed through [dysentery](https://github.com/Deep-Symmetry/dysentery)?
When I load a track from the USB stick I see packet changes through Dysentery

**Comment by brunchboy** [comment] 2020-02-03 01:21
Dysentery is a nice way to get a visual overview of changes from packet to packet, but it can’t show you what rekordbox is sending to the XDJ-XZ,  because it is not involved in that communication path. For that you need a Wireshark capture in promiscuous mode.

**Comment by brunchboy** [comment] 2020-02-03 01:23
Can I infer from this that you have been able to tell the XDJ to load tracks using rekordbox? If so, there must be a way to do it, and packet captures will be the key to figuring that out.

**Comment by christophdebaene** [comment] 2020-02-03 20:35
One configuration setup is to load tracks that are located on you're laptop and loading them to XDJ via rekordbox.

The configuration I speak about, is through USB stick on XDJ. As far that I know, it's not possible through rekordbox to navigate through the tracks that are located on the USB stick. Therefore hard to find out which packet is necessary to make it work.

But through you're library I noticed that you can in fact browse through the collection that is located on the USB stick. The fact that there is 'Load' button implemented I thought that there was the possibility. It's the only feature that is missing that I would like to have :)

Do I understand correctly that the 'Load' works on a CDJ for example?

**Comment by brunchboy** [comment] 2020-02-03 20:45
You understand correctly. You can see the exact message it uses in Section 10 (page 66, Figure 58) of the dysentery protocol analysis paper, https://deepsymmetry.org/dysentery/Analysis.pdf

When rekordbox sends that to tell a player to load a track from its own collection, it send Dr, Sr, and Tr, and rekordbox ID values that correspond to itself and its collection. Through experimentation, we discovered that if you send Dr, Sr, Tr, and rekordbox ID values that instead correspond to a USB or SD slot on another player, CDJs and the XDJ-1000 will still load those tracks. It sounds like from your experimentation, however, that the XDJ-XZ will not. And, as you pointed out yourself, because Pioneer doesn’t officially support that through any user interface, it’s not too surprising that the developers of the XDJ-XZ would not have implemented it.

**Comment by christophdebaene** [comment] 2020-02-03 23:37
Thank you for you're feedback and awesome work you already did on this project!

Given the following video [PIONEER XDJ-XZ SET UP WITH TWO CDJ-2000 PLAYING OFF ONE USB](https://www.youtube.com/watch?v=n0qOIDcqGhs). 
It loads a track that is on a usb stick from a CDJ device, wouldn't that mean that it should be possible on the XDJ-XZ?

**Comment by brunchboy** [comment] 2020-02-04 01:26
From what I could see in that video, they load a track on the XDJ-XZ from a CDJ USB using the controls on the XDJ-XZ. What you are trying to do is remotely tell the XDJ-XZ to load a track from a CDJ USB. Have you found any evidence that works? You have already tried the only way anyone knows how to attempt that, which is using the network packet I described above, and which Beat Link Trigger sends when you press the Load button, and it did not work, isn’t that true?

**Comment by brunchboy** [comment] 2020-02-04 01:29
Unless you can find some other system that is able to successfully remotely tell the XDJ-XZ to load a track, and capture the network traffic that it uses to achieve that so that we can try to reproduce it, there is nothing to go on. I don’t have any reason to believe it is possible given what you have told me, but you are the best person to answer these questions since you actually have access to an XDJ-XZ! 😄 I only have my 2000 nexus setup.

**Comment by joelpujoldj** [comment] 2020-02-16 14:15
So, i have the XDJ-XZ and maybe I can help.

Gonna try to install this later, so maybe my comments our outdated.

I’ve read all the threat, and nobody mention one option of the XDJ in the menu: send MIDI: ON/OFF

This maybe the key of it.

Plus, it could be a different process to play from a usb stick than from rekordbox that could affect the sync functionality.

Anyway, thanks for the software and the interest! Going to follow it. 🙌🙂

Cheers

**Comment by brunchboy** [comment] 2020-02-16 19:48
Hello, @joelpujoldj and welcome! MIDI is  not involved in the Pro DJ Link protocol in any way, unfortunately. If you would like to learn all the details we understand, you can read the analysis PDF that i linked to five comments above. If you are able to find a way to remotely cause the XDJ to load a track from one of its USB slots, and capture the network traffic which achieves that, please share it! I still believe the most likely answer is simply that there is n way to do this.

**Comment by brunchboy** [comment] 2020-03-29 22:18
I think I know how to fix this! Someone noticed that there is a new byte in the load track packet that didn’t exist before, and I now realize must have been added for the XDJ-XZ. Without that value, it has no way of knowing which deck it is supposed to load a track into (because it is the first player that has multiple decks but only one network address). I am going to add that byte to the Beat Link Library and re-publish the preview release Beat Link Trigger. I’ll let you know when that is done, and I hope you will be able to test the preview release and let me know if it fixes this issue.

**Comment by brunchboy** [comment] 2020-03-29 22:45
Ok, @christophdebaene the preview has been updated with this change. Could you let me know if it can now load tracks on your XDJ-XZ?

**Comment by christophdebaene** [comment] 2020-03-30 19:14
You mean trying the v0.6.2-SNAPSHOT release?

**Comment by brunchboy** [comment] 2020-03-30 19:22
Yes, I mean the version of the snapshot release I published last night. Thanks!

**Comment by christophdebaene** [comment] 2020-03-30 19:39
I upgraded to the latest firmware of the XDJ-XZ [1.10](https://www.pioneerdj.com/en-us/support/software/all-in-one-system/xdj-xz/#firmware-update).
I tried with version [v0.6.2-SNAPSHOT](https://github.com/Deep-Symmetry/beat-link-trigger/releases/download/v0.6.2-SNAPSHOT/Beat-Link-Trigger-0.6.2-Preview-Win64.msi) but unfortunately it doesn't work.

Is the version 0.6.2 release of last night?

**Comment by brunchboy** [comment] 2020-03-30 19:42
I’m sorry, but the question doesn’t make sense to me. I published a snapshot last night. A snapshot isn’t a version, it’s something that tracks ongoing development. (To see when it was built you can look at the actual timestamp in the jar).

Anyway, that is unfortunate. So I am back to waiting for you (or someone) to take a Wireshark capture of rekordbox successfully doing this and uploading it to see if we can find a detail that can be emulated.

**Comment by Swiftb0y** [comment] 2020-03-30 21:04
I guess this was only part of the puzzle. Once the musicstores open again, I'll try to do a "test session" with an XZ and grab a capture while I'm at it. :wink:

**Comment by brunchboy** [comment] 2020-03-30 21:46
That would be great, but hopefully someone who owns one can do it too. 😄

Also, since this is Beat Link Trigger we are talking about, there is an easier way to tell when a snapshot was built, that information shows up when you open the About box.

**Comment by brunchboy** [comment] 2020-04-11 21:37
I want to do a release of BLT this weekend, and would have liked to have a fix for this included, but have not received the Wireshark capture I would need. Although I guess it is still not clear to me exactly how much works or does not. Could someone confirm whether:

1. Rekordbox is able to tell the XDJ-XJ to load a track using its GUI.
2. BLT is able to tell the XDJ-XZ to load a track from rekordbox using the **Load Track on Player** interface.

(I know that this fails when BLT tries to tell it to load a track from a USB stick, but does it work to load from a rekordbox collection? To test that would require a separate computer for rekordox and BLT, of course.)

If point 2 _does_ work, then there is perhaps nothing we can do in order to fix this, the XDJ-XZ may simply not support remote track load instructions of that format. But if point 1 works and point 2 does not, then a Wireshark capture could help us figure out what we are doing different, and thus perhaps enable remote loading tracks even from USB. @christophdebaene and @joelpujoldj  could you perhaps investigate these details this weekend?

**Comment by brunchboy** [comment] 2020-04-11 21:45
And, of course, if not even point 1 works in my question above, and not even rekordbox can tell the XDJ-XZ remotely to load a track, then it means that it simply lacks this feature, and there is no point trying to support it, I would just have to update the user guide, and maybe hide the option in the user interface when the player is an XDJ-XZ.

**Comment by christophdebaene** [comment] 2020-04-15 21:02
Loading a track that resides on the USB from rekordbox is not possible. Even browsing through the collection is not possible. Only the files that are stored on the computer. I guess its the same when connecting a CDJ?

The fact that you implemented the feature, means that you can browse a track on CDJ A and load it onto CDJ B, without even the rekordbox software?

What need to be tested, is connecting a CDJ with a XDJ-XZ and trying if a track van be selected from the CDJ and loaded to the XDJ-XZ, is that correct?

**Comment by brunchboy** [comment] 2020-04-15 21:06
Loading a track on a CDJ from rekordbox using the rekordbox GUI is possible. Doing that sends a message to the the CDJ that can be captured and analyzed. By analyzing that, we were able to figure out how to send a message that would tell a CDJ to load a track (on USB or SD) from itself or another CDJ, and verify that it worked.

However, it seems that message does not work with the XDJ-XZ.

Therefore what I am waiting for is for someone to try loading a track from rekordbox onto the XDJ-XZ using the rekordbox GUI. Is that even possible? If so, then we have one piece of information. Then we need to capture the network message that was sent by rekordbox to make that happen, and compare it to the ones that are sent to make CDJs do the same thing, to see if there is a difference in the messages as we understand them, which would allow us to change the messages that we send and make this work with the XDJ-XZ. Or it may simply be that this feature only works with CDJs, not with the XDJ-XZ.

**Comment by christophdebaene** [comment] 2020-04-15 23:25
What I noticed is that the player status (waveform, progress, etc.) only works when you play a track from the USB. When a track is played from rekordbox (mp3 on pc) then the player status doesn't show anything.

I did a Wireshark capture when I load a track on the XDJ-XZ device itself from a USB stick.
Wireshark capture: [xdj-xz.zip](https://github.com/Deep-Symmetry/beat-link-trigger/files/4484131/xdj-xz.zip)

**Comment by brunchboy** [comment] 2020-04-15 23:29
Unfortunately, that will not help, because it does not involve a remote command telling the XDJ-XZ to load the track. There will be no network traffic involved. I need a capture of rekordbox telling the XDJ-XZ to load a track remotely.

Yours is the first report of player status not showing rekordbox tracks, I believe that has worked for other people. Are there any errors in the log when that happens? And you are running Beat Link Trigger on a different computer than rekordbox?

**Comment by brunchboy** [comment] 2020-04-25 05:48
My XDJ-XZ arrived today, and after some experimentation I can confirm that it will not load tracks when anything other than rekordbox tells it to. I am updating the user interface in Beat Link Trigger to reflect this limitation of that hardware.

**Comment by brunchboy** [comment] 2020-04-25 06:18
I was also able to reproduce the problem you had with tracks loaded from rekordbox, but only with the release version of Beat Link Trigger. The preview release incorporates a fix to handle nxs2 cue lists that are missing information we expected would be there, and this solves the missing rekordbox track data problem. Please let me know if that is not the case for you.

**Closed** 2020-04-25 06:42 UTC
Labels: help wanted

**Comment by brunchboy** [comment] 2020-05-09 08:15
@christophdebaene were you using rekordbox 6? That wasn’t compatible with Beat Link Trigger in export mode at all until today. I have just pushed an updated preview build that fixes that, and a few other rekordbox 6 issues. I have also found a way to make the XDJ-XZ load tracks, but it will _only_ do that if rekordbox or rekordbox mobile is also on the network, so we can “borrow” their device number in the instruction we send to load a track. I plan to publish a new official release with all of these features after I get some sleep. 😄
