### ISSUE TITLE
No Metadata in RB 6

### ISSUE THREAD

**Issue by KayPure** [Deep-Symmetry/beat-link-trigger#103] opened 2020-05-09 01:59 UTC
Just FYI.

Rekorbox 6 released some weeks ago. After i update my RB to v6, Metadata is not displayed anymore. 

Switching back to v5 and the Metadata is displayed correctly. I changed few Settings and switch between v5 and v6. But no settings will let me display the Metadata in v6, only in v5. Perhaps some changes from Pioneer!? Will stay on 5 for a while now ;)

Cheers

RB in Exportmode on a Windows PC
BLT on a second Windows PC
2 XDJ 1000MK2

**Comment by brunchboy** [comment] 2020-05-09 02:09
Yes, this is mentioned in a warning at the top of the project home page. It may be possible to support rekordbox 6 someday, nobody knows yet. Could you please attach the log files, and associated rekordbox export files, to this issue? That will help start the process of understanding and fixing things.

**Comment by brunchboy** [comment] 2020-05-09 02:12
Your logs are needed because others have been able to use rekordbox 6 without issue, so there must be something particular about the tracks that you analyzed with rekordbox 6 which are causing problems for our efforts to parse the exported data.

**Comment by brunchboy** [comment] 2020-05-09 02:15
Although, actually, in your case since you are talking about export mode, it will be log files and Wireshark network captures. Even the log files will be interesting, though, because the other situation we had heard of so far was Netsky using it with a USB. So in your case it is Beat Link running into trouble directly when talking to rekordbox, whereas in Netsky’s case it was Crate Digger trying to parse the downloaded exports from the USB. See https://github.com/Deep-Symmetry/beat-link/issues/42

**Closed** 2020-05-09 04:57 UTC
Labels: enhancement, help wanted

**Comment by brunchboy** [comment] 2020-05-09 05:31
@KayPure I was planning to wait until publishing the release I’ve been working up to this weekend before trying to tackle any sort of rekordbox 6 testing and compatibility efforts. But since you’re the second person who has run into something now, I decided to install it on a separate computer and see if I could reproduce your problem. And the good news is that I was, and I could see what had changed in the way rekordbox 6 responds to database queries, and make a change to Beat Link to be compatible with its new responses. This seems to be working for me now. Could you try downloading the latest preview (snapshot) build, and let me know if it works for you with rekordbox 6 as well? https://github.com/Deep-Symmetry/beat-link-trigger/releases/tag/v0.6.2-SNAPSHOT

**Comment by KayPure** [comment] 2020-05-10 19:52
im already on the snapshot version. still no luck. since i dont know how to use wireshark in this case, i can only provide the blt log file, perhaps this will help? i guess this error code has something todo with it

> 2020-May-10 21:48:34 ERROR [org.deepsymmetry.beatlink.data.MetadataFinder:124] - Problem requesting metadata, returning null
                                                        java.lang.Thread.run                              
                         org.deepsymmetry.beatlink.data.MetadataFinder$7.run     MetadataFinder.java: 1403
                    org.deepsymmetry.beatlink.data.MetadataFinder.access$500     MetadataFinder.java:   39
       org.deepsymmetry.beatlink.data.MetadataFinder.requestMetadataInternal     MetadataFinder.java:  122
org.deepsymmetry.beatlink.dbserver.ConnectionManager.invokeWithClientSession  ConnectionManager.java:  192
         org.deepsymmetry.beatlink.dbserver.ConnectionManager.allocateClient  ConnectionManager.java:  124
                            org.deepsymmetry.beatlink.dbserver.Client.<init>             Client.java:  101
              org.deepsymmetry.beatlink.dbserver.Client.performSetupExchange             Client.java:  120
                             org.deepsymmetry.beatlink.dbserver.Message.read            Message.java:  910
                                                     java.nio.ByteBuffer.get                              
                                                 java.nio.HeapByteBuffer.get                              
java.nio.BufferUnderflowException: 

Full log attached
[blt.log](https://github.com/Deep-Symmetry/beat-link-trigger/files/4606650/blt.log)

will try to do a full wireshark log if i got some spare time to figure out how to do it exactly.

**Comment by brunchboy** [comment] 2020-05-10 19:56
Just to clarify, there is no one single “snapshot” version. The meaning of snapshot releases is that they evolve over time, so you need to download them fresh every time you want to test them. You can see when the one you were using was built by looking in the About box. It is almost certainly older than the one where I fixed this problem. Could you try downloading it again and seeing?

Thanks!

**Comment by brunchboy** [comment] 2020-05-10 20:02
Thanks for including the full log. By looking at the top of it, I can see you are running a snapshot build from May 7. I figured out how to read data from rekordbox 6 in export mode on May 8, so there is a good chance that if you update your download to the current build, it will work. As I am typing this, the second release candidate is building (which includes a discovery contributed by the Mixxx DJ developers about how to detect the colors that have been assigned to ordinary memory points and loops).

**Comment by brunchboy** [comment] 2020-05-10 20:06
I am getting ready to publish the next actual release of Beat Link Trigger, so if you happen to have a chance to see if the current build works with your rekordbox 6 in the next few minutes, that would be wonderful. Otherwise I will just cross my fingers and do the release anyway, as I am not yet promising everything is great with rekordbox 6. 😄

**Comment by KayPure** [comment] 2020-05-10 20:08
oh, ok. totally missunderstood the releases i guess. will try the newest, thanks. give me few minutes to fire everything up and download the latest release.

**Comment by brunchboy** [comment] 2020-05-10 20:11
Thank you, that is great! And no apology necessary, people who are not Java developers are not familiar with the special meaning of the word “SNAPSHOT” so I try to be clear in my descriptions, but there is a ton of information about this project to digest all at once. Every _other_ kind of release is a real, permanent release that will never change (in fact, the infrastructure prevents you from changing it once released). But snapshot releases are a way to let people try things as they evolve, before committing to a final release. Without them I would go through release numbers like mad. 😄

**Comment by KayPure** [comment] 2020-05-10 20:15
seems legit ;) 
ok, so the newest snapshot works with rb6 in export mode. only thing i notice: i has to fire up blt after i turn on the xdj and rb6. if i fire up blt at first, it will not display it. but thats not a big deal ;) thanks brunchboy!

**Comment by brunchboy** [comment] 2020-05-10 20:32
That’s great news, thank you for testing for me. I am curious what is happening when you start BLT first. Do you have your BLT configured to use a real player number? If so, it may end up using a player number that the XDJ is using as well, leading to problems. There is no rush on this, but if you could share a log file from when this happens, I might be able to do something about it. But in general, I would recommend bringing up your DJ hardware first and adding BLT later, especially if you are having it use a real player number.

**Comment by KayPure** [comment] 2020-05-10 20:39
just tested it and now it works. no matter in which order i start. perhaps i was too fast in close and reopen everything and something messed up. if this happen again, i will post a log file. 

its configured to use **not** a real player number.

**Comment by brunchboy** [comment] 2020-05-10 20:40
Ok, great! Thanks again. I will release with more confidence this afternoon then.
